# Helper script to generate web pages for the site

from xml.dom import minidom
from xml.parsers.expat import ExpatError
import sys

def usage():
	print(sys.argv[0] + " <filename.html>")
	sys.exit(2)

def main():
	nav = None
	ul = None
	doc_div = None
	containers = list()

	if len(sys.argv) != 2:
		usage()

	filename = sys.argv[-1]	

	try:
		doc = minidom.parse(filename)
	except (IOError, ExpatError), e:
		print(e)
		sys.exit(1)

	# Add bootstrap meta tags to <head>
	metas = doc.getElementsByTagName("meta")
	for m in metas:
		head = m.parentNode
		head.removeChild(m)

	meta1 = doc.createElement("meta")
	meta1.setAttribute("charset", "utf-8")

	meta2 = doc.createElement("meta")
	meta2.setAttribute("content", "IE=edge")
	meta2.setAttribute("http-equiv", "X-UA-Compatible")
	
	meta3 = doc.createElement("meta")
	meta3.setAttribute("content", "width=device-width, initial-scale=1")
	meta3.setAttribute("name", "viewport")

	head = doc.getElementsByTagName("head")[0]
	head.insertBefore(meta3,head.firstChild)
	head.insertBefore(meta2,meta3)
	head.insertBefore(meta1,meta2)

	# Add bootstrap class to all <h1>
	h1_list = doc.getElementsByTagName("h1")
	for h1 in h1_list:
		h1.setAttribute("class", "page-header")

	# Find <nav class="col-md-3"> so we can add TOC nav to it
	nav_list = doc.getElementsByTagName("nav")
	for n in nav_list:
		if n.hasAttributes() and n.getAttribute("class") == "col-md-3":
			nav = n

	div_list = doc.getElementsByTagName("div")
	for div in div_list:
		# Find <div class="document">, for removal
		if div.hasAttributes() and div.getAttribute("class") == "document":
			doc_div = div
		# Find <div class="col-md-3" so we can add TOC nav to it
		# if div.hasAttributes() and div.getAttribute("class") == "col-md-3":
		# 	nav = div
		# Find TOC generated by rst2html
		if div.hasAttribute("id") and div.getAttribute("id") == "contents":
			contents_div = div
			for node in div.childNodes:				
				if node.nodeType != node.TEXT_NODE: 
					if node.tagName == "ul":
						ul = node
		# Remove id from divs added by rst2html
		# if div.hasAttribute("class") and div.getAttribute("class") == "section":
		# 	if div.hasAttribute("id"):
		# 		div.removeAttribute("id")

	# Insert TOC as a sidebar nav
	if ul is not None and nav is not None:
		ul.setAttribute("class", "nav nav-pills nav-stacked hidden-xs hidden-sm")
		ul.setAttribute("data-spy", "affix")
		ul.setAttribute("data-offset-top", "51")
		nav.appendChild(ul)
		contents_div.parentNode.removeChild(contents_div)

		# Now fix all the sub-nav links
		for li in ul.childNodes:
			if li.nodeType not in (li.TEXT_NODE, li.COMMENT_NODE) and li.tagName == "li":
				for node in li.childNodes:
					if node.nodeType not in (node.TEXT_NODE, node.COMMENT_NODE) and node.tagName == "ul":
						node.setAttribute("class", "nav nav-pills nav-stacked sub-nav")

	for node in doc_div.childNodes:
		if node.nodeType not in (node.TEXT_NODE, node.COMMENT_NODE) and (node.tagName == "div" or node.tagName == "nav"):
			containers.append(node.cloneNode(deep=True))	

			# if node.hasAttributes and node.getAttribute("class") == "container":	
			# 	containers.append(node.cloneNode(deep=True))

	# Make all images responsive
	img_list = doc.getElementsByTagName("img")
	for img in img_list:
		img.setAttribute("class", "img-responsive")
		# clone = i.cloneNode(deep=True)

		# panel = doc.createElement("div")
		# panel.setAttribute("class", "panel")

		# panelbody = doc.createElement("div")
		# panelbody.setAttribute("class", "panel-body")

		# # panelbody.appendChild(clone)
		# panel.appendChild(panelbody)

		# print panel.getAttribute("class")
		# p = i.parentNode
		# p.replaceChild(panel,i)

		# print p.getAttribute("class")

	# # Remove up all section header <a> tags
	# a_tags = doc.getElementsByTagName("a")
	# for a in a_tags:
	# 	if a.hasAttribute("class") and a.getAttribute("class") == "toc-backref":			
	# 		text = a.firstChild
	# 		p = a.parentNode

	# 		# p.removeChild(a)
	# 		# a.unlink()
	# 		# print(a)
	# 		p.replaceChild(text, a)			
	# 		# p.appendChild(text)
			
	scripts = doc.getElementsByTagName("script")
	footers = doc.getElementsByTagName("footer")
				
	body = doc_div.parentNode

	# scrollspy and affix attributes
	body.setAttribute("data-spy", "scroll")
	body.setAttribute("data-target", "#sidenav")
	body.setAttribute("data-offset", "15")

	# Remove extra <div class="document">
	# containers is found earlier in the code
	if containers:		
		for c in containers:
			body.appendChild(c)
		for f in footers:
			body.appendChild(f)
		for s in scripts:
			body.appendChild(s)
		body.removeChild(doc_div)

	# Write file to disk
	f = open(filename, "wb")
	f.write(doc.toxml().encode('UTF-8'))


if __name__ == "__main__":
	main()
