#!/bin/ksh

for p in `px status | sed 's/^\* //' | awk '{print $2}'`; do

    NP=`ps -flade | grep ' '$p' ' | grep -v grep | grep -v status | wc -l`;

    if ((NP!=1)); then
       echo $p ' ' $NP
    fi

done 
